10dlc ext api update
plivo/plivo-java pull request #212
Opened 2022-07-14 05:26 UTC by manas-plivo

2022-08-16 03:50 UTC, narayana-plivo requested changes
Please add the UT for new changes

2022-09-01 10:34 UTC, renoldthomas-plivo commented
> Please add the UT for new changes

Hi Narayana, Mam has told UT need not be a blocker for Deployment. Could you please approve the PR. Thank You

2022-09-01 10:38 UTC, neeraj-plivo approved these changes

2022-09-01 10:52 UTC, narayana-plivo approved these changes

2022-09-01 10:54 UTC, merged