Sms 4444 sdk 10dlc enhancement
plivo/plivo-java pull request #216
Opened 2022-09-09 12:48 UTC by NirmitiJain

2022-09-13 05:21 UTC, prashantjha-plivo requested changes

2022-09-13 05:28 UTC, NirmitiJain commented on src/main/java/com/plivo/api/models/brand/BrandUsecaseResponse.java
> +    public String getBrandId() {
As per requirement, we need to return field called "brand_id"
and extending BaseResource mandates overriding getId()

2022-09-13 18:20 UTC, narayana-plivo commented on src/main/java/com/plivo/api/PlivoAPIService.java
> +  @GET("Account/{authId}/10dlc/Brand/{id}/usecases/")
nit : usecases => Usecases

2022-09-13 18:23 UTC, narayana-plivo commented on src/main/java/com/plivo/api/models/brand/BrandUsecase.java
> +  private List<useCase> useCases = new ArrayList<useCase>();
nit: useCase => UseCase

2022-09-13 18:24 UTC, narayana-plivo commented on src/main/java/com/plivo/api/models/brand/useCase.java
> +public class useCase {
class name should be capital letter

2022-09-13 18:24 UTC, narayana-plivo commented on src/main/java/com/plivo/api/models/brand/useCase.java
> +    private String details;
details or detail?

2022-09-13 18:26 UTC, narayana-plivo requested changes
@NirmitiJain please address the request change and update the versions

2022-09-14 05:35 UTC, NirmitiJain commented on src/main/java/com/plivo/api/models/brand/useCase.java
> +    private String details;
It's "details" as per PRD

2022-09-22 03:19 UTC, narayana-plivo commented on README.md
> +  <version>6.13.0</version>
please update 5.14.0

2022-09-22 03:20 UTC, narayana-plivo approved these changes
LGTM. Good job @NirmitiJain

2022-10-12 03:08 UTC, narayana-plivo commented
@NirmitiJain Build and UT is failing. Please check

2022-10-12 03:08 UTC, narayana-plivo requested changes
Please fix UT and Build

2022-10-17 10:26 UTC, prashantjha-plivo approved these changes
LGTM

2022-10-17 10:33 UTC, merged